services:
  app:
    build:
      context: .
      dockerfile: ./memcached/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - memcached
      - db 
    volumes:
      - ./memcached:/app
    environment:
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11211:11211"

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"